[DEFAULT]
; Cluster filesystem layout supplied by the user.
CSL_DIR = /project/sdodelso/joannjones/cosmosis-standard-library
THAWINGDE_DIR = /project/sdodelso/joannjones/cosmosis-standard-library/thawingde
