; Standard CosmoSIS consistency modules required by all pipelines.
[consistency]
file = utility/consistency/consistency_interface.py

[bbn_consistency]
file = utility/bbn_consistency/bbn_consistency.py
