; ΛCDM cosmology block for CMB runs.
; Identical to cosmology_cmb_thaw_nec.ini except w = -1 (fixed)
; and wa is fixed to the prior midpoint.
[cosmological_parameters]
h0      = 0.58  0.68  0.80
omega_m = 0.10  0.31  0.60
omega_b = 0.03  0.049 0.07
n_s     = 0.93  0.965 1.00
A_s_1e9 = 0.5   2.1   5.0
w       = -1.0
wa      = 1.45
tau     = 0.01  0.054 0.8
omega_k = 0.0
yhe     = 0.245341
standard_neutrino_neff = 3.044
num_massive_neutrinos  = 3
nnu     = 3.044
mnu     = 0.06 0.0773062 0.6
k_s     = 0.05
n_run   = 0.0
r_t     = 0.0
n_t     = 0.0
