; ΛCDM cosmology block for DES Y6 3x2pt runs.
; Identical to cosmology_y6_3x2_thaw_nec.ini except w = -1 (fixed)
; and wa is fixed to the prior midpoint.
[cosmological_parameters]
h0      = 0.58 0.69 0.80
omega_m = 0.1  0.31 0.6
omega_b = 0.03 0.051 0.07
n_s     = 0.93 0.965 1.00
A_s_1e9 = 0.5  1.831 5.0
w       = -1.0
wa      = 1.45
omega_k = 0.0
tau     = 0.054
yhe     = 0.245341
standard_neutrino_neff = 3.044
num_massive_neutrinos  = 3
nnu     = 3.044
mnu     = 0.06 0.0773062 0.6
