; Planck 2018 plik_lite nuisance parameter.
; Only one nuisance parameter for the lite likelihood (all foreground
; and calibration parameters have been analytically marginalized).
[planck]
a_planck = 0.9  1.0  1.1
