; Values for Shajib+2025 Planck+ACT CMB run (no SPT-3G).
%include thawingde/ini/values/cosmology_shajib_cmb_thaw_nec.ini
%include thawingde/ini/values/planck_nuisance.ini
%include thawingde/ini/values/act_nuisance.ini
